// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Alias {
  name: string;
  content: string;
  author: string;
  createdAt: bigint;
}
