// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AliasType } from "./AliasType";

export interface PostAlias {
  name: string;
  content: string;
  type: AliasType;
}
