// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AliasType } from "./AliasType";

export interface PutAlias {
  content: string | null;
  type: AliasType | null;
}
