name: Test building front end

on:
  pull_request:
    paths:
      - 'frontend/**'

jobs:
  deploy:
    name: Test building frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
    - uses: actions/checkout@master

    - name: Install NPM packages
      run: npm install
      
    - name: Build NPM project
      run: npm run build
